// resources/js/components/DatabaseListItem.vue
<template>
  <li class="dbs-list-item p-0 " :class="classes">
    <a href="#" class="menu-item animated fadeIn d-block" @click="toggleDbItem">
      <i class="fa tree-toggle-icon text-gray-dark mr-1" :class="{'fa-caret-down': open, 'fa-caret-right': !open}"></i>
      <i class="fa fa-database db-icon mr-1"></i>
      {{db.name}}
    </a>
    <template v-if="colls.length">
      <CollectionsList :colls="colls"></CollectionsList>
    </template>
  </li>
</template>

<script>
import { mapGetters } from 'vuex'
import CollectionsList from './CollectionsList'
import _ from 'lodash'

export default {
  props: {
    db: {
      type: Object
    }
  },

  components: {
    CollectionsList
  },

  data() {
    return {
      open: false,
      firstOpen: false
    }
  },

  methods: {
    toggleDbItem(e) {
      e.preventDefault()
      if(!this.open && !this.firstOpen) {
        this.$store.dispatch('fetchColls', this.db.name)
      }
      this.firstOpen = true
      this.open = !this.open
    }
  },

  computed: {
    ...mapGetters({
      collsByDb: 'collsByDb'
    }),
    colls() {
      var colls = this.collsByDb(this.db.name)
      if (colls) {
        return colls;
      }
      return []
    },
    classes() {
      return this.open ? 'open' : ''
    },
  }
}
</script>

// client/js/components/DatabaseListItem.jsx
import React, { PropTypes, Component } from 'react'
import ReactDOM from 'react-dom'
import CollectionsList from './CollectionsList'
import CollectionsContainer from '../containers/CollectionsContainer'

export default class DatabaseListItem extends Component {
  constructor() {
    super()
    this.state = {
      open: false,
      firstOpen: false
    }
  }

  propTypes: {
    db: PropTypes.object,
  }

  onClickHandler(e) {
    e.preventDefault()
    this.setState({
      firstOpen: true,
      open: !this.state.open
    })
  }

  renderCollections(dbName) {
    if (this.state.firstOpen) {
      return (
        <CollectionsContainer dbName={dbName} />
      )
    }
  }

  render() {
    const db = this.props.db
    let classes = 'menu-item dbs-list-item'
    classes += this.state.open ? 'open' : ''
    return (
      <li class={classes} key={db.name}>
        <a href="#" class="animated fadeIn" onClick={this.onClickHandler.bind(this)}>
          <i class="fa fa-fw fa-caret-right tree-toggle-icon"></i>
          <i class="fa fa-fw fa-database db-icon"></i>
          {db.name}
        </a>
        <div class="collection-list">
          {this.renderCollections(db.name)}
        </div>
      </li>
    )
  }
}
