// client/bk/components/DatabaseListItem.jsx
import React, { PropTypes, Component } from 'react'
import ReactDOM from 'react-dom'
import CollectionsContainer from '../containers/CollectionsContainer'

export default class DatabaseListItem extends Component {
  constructor() {
    super()
    this.state = {
      open: false,
      firstOpen: false
    }
  }

  propTypes: {
    db: PropTypes.object,
  }

  onClickHandler(e) {
    e.preventDefault()
    this.setState({
      firstOpen: true,
      open: !this.state.open
    })
  }

  renderCollections(dbName) {
    if (this.state.firstOpen) {
      return (
        <CollectionsContainer dbName={dbName} />
      )
    }
  }

  render() {
    const db = this.props.db
    let classes = 'menu-item dbs-list-item'
    classes += this.state.open ? 'open' : ''
    return (
      <li class={classes} key={db.name}>
        <a href="#" class="animated fadeIn" onClick={this.onClickHandler.bind(this)}>
          <i class="fa fa-fw fa-caret-right tree-toggle-icon"></i>
          <i class="fa fa-fw fa-database db-icon"></i>
          {db.name}
        </a>
        <div class="collection-list">
          {this.renderCollections(db.name)}
        </div>
      </li>
    )
  }
}

// client/js/components/DatabaseListItem.vue
<template>
  <li class="menu-item dbs-list-item" :class="classes">
    <a href="#" class="animated fadeIn" @click="onClickHandler">
      <i class="fa fa-fw fa-caret-right tree-toggle-icon"></i>
      <i class="fa fa-fw fa-database db-icon"></i>
      {{db.name}}
    </a>
    <div class="collection-list">
      <!-- {this.renderCollections(db.name)} -->
      collectios
    </div>
  </li>
</template>

<script>
export default {
  props: {
    db: {
      type: Object
    }
  },

  data() {
    return {
      open: false,
      firstOpen: false
    }
  },

  methods: {
    onClickHandler(e) {
      e.preventDefault()
      this.firstOpen = true
      this.open = !this.open
    }
  },

  computed: {
    classes() {
      return this.open ? 'open' : ''
    }
  }
}
</script>
