// resources/js/components/Layout.vue
<template>
      <div>
        <Navbar />
        <div class="container-xl">
          <div class="columns">
            <div class="one-fifth column">
              <DatabasesList></DatabasesList>
            </div>
            <div class="four-fifth column">
              <!-- {this.props.children} -->
            </div>
          </div>
        </div>
      </div>
</template>
<script>
import Navbar from './Navbar'
import DatabasesList from './DatabasesList'

export default {
  components: {
    Navbar,
    DatabasesList
  }
}
</script>

<style scoped>
.container-xl {
  padding-top: 20px;
}
</style>

// client/js/components/Layout.jsx
import React, { Component } from 'react'
import DatabasesContainer from '../containers/DatabasesContainer'
import Navbar from './Navbar'

export default class Layout extends Component {
	render() {
    const style = {
      paddingTop: 20
    }
		return (
      <div>
        <Navbar />
    		<div class="container" style={style}>
          <div class="columns">
            <div class="one-fifth column">
              <DatabasesContainer />
            </div>
            <div class="four-fifths column">
              {this.props.children}
            </div>
    			</div>
        </div>
      </div>
		)
	}
}
