// client/js/components/Navbar.jsx
import React, { Component } from 'react'

export default class TopNavbar extends Component {
  render() {
    return (
      <header>
        <div class="container">
          <a href="#" class="brand-title">Home</a>
          <nav class="pull-right">
            <a href="#">Settings</a>
            <a href="#">About</a>
          </nav>
        </div>
      </header>
    )
  }
}

// client/js/components/Navbar.vue
<template>
  <header class="bg-gray border-bottom">
    <div class="container-xl">
      <a href="#" class="brand-title"><b>Home</b></a>
      <nav class="pull-right">
        <a href="#"><b>Settings</b></a>
        <a href="#"><b>Settings</b></a>
      </nav>
    </div>
  </header>
</template>
<script>
export default {
}
</script>
