// client/js/components/DatabaseListItem.vue
<template>
  <li class="menu-item dbs-list-item" :class="classes">
    <a href="#" class="animated fadeIn" @click="onClickHandler">
      <i class="fa fa-fw fa-caret-right tree-toggle-icon"></i>
      <i class="fa fa-fw fa-database db-icon"></i>
      {{db.name}}
    </a>
    <div class="collection-list">
      <!-- {this.renderCollections(db.name)} -->
      collectios
    </div>
  </li>
</template>

<script>
export default {
  props: {
    db: {
      type: Object
    }
  },

  data() {
    return {
      open: false,
      firstOpen: false
    }
  },

  methods: {
    onClickHandler(e) {
      e.preventDefault()
      this.firstOpen = true
      this.open = !this.open
    }
  },

  computed: {
    classes() {
      return this.open ? 'open' : ''
    }
  }
}
</script>

// client/components/DatabaseListItem.jsx
import React, { Component } from 'react'
import ReactDOM from 'react-dom'

export default class DatabaseListItem extends Component {
  constructor() {
    super()
  }

  onClickHandler(e) {
    e.preventDefault()
  }

  render() {
    const db = this.props.db;
    return (
      <li class="list-group-item" key={db.name} ref="list">
        <a href="#" class="animated fadeIn" onClick={this.onClickHandler}>
          <i class="fa fa-fw fa-database"></i>
          {db.name}
        </a>
      </li>
    )
  }
}
